Hopefully fix crazy renaming issues on all OSes

diff --git a/templates/new b/templates/new
--- a/templates/new
+++ b/templates/new
@@ -4,41 +4,42 @@ set -e
 
 cli_args="${@}"
 cwd=$(pwd)
-examples_dir=$(dirname "$(readlink -f "$0")")
+templates_dir=$(dirname "$(readlink -f "$0")")
 
-project_name="$1"
-project_dir="$cwd/$project_name"
+export BEAMUP_PROJECT_NAME="$1"
+project_dir="$cwd/$BEAMUP_PROJECT_NAME"
 template="erlang"
 
-# Copy template to new project folder
-mkdir "$project_name" || fail "Directory already exists"
-cp -R "$examples_dir/$template/." "$project_dir/"
-cd $project_name
+fail () {
+  echo "Failed to create project: $1"
+  exit 1
+}
 
-# Replace `beamup_project_name` placeholder with $project_name
-replace_pattern="s/beamup_project_name/$project_name/"
+# Copy template to new project folder
+mkdir "$BEAMUP_PROJECT_NAME" || fail "Directory already exists"
+cp -R "$templates_dir/$template/." "$project_dir/"
+cd $BEAMUP_PROJECT_NAME
+
+# Replace `beamup_project_name` placeholder with $BEAMUP_PROJECT_NAME
+replace_pattern="s/beamup_project_name/$BEAMUP_PROJECT_NAME/"
+
 
 # replace in file contents
 perl -pi -w -e "$replace_pattern;" $( grep -rl "beamup_project_name" . )
 
 # rename directories depth-first
-find . -depth "$project_dir" -type d -execdir rename "$replace_pattern" '{}' \;
+find "$project_dir" -depth -type d -exec $templates_dir/rename_dir '{}' \;
 
 # rename files
-find . -exec rename "$replace_pattern" '{}' \;
+find "$project_dir" -type f -exec $templates_dir/rename_file '{}' \;
 
 git init
 git add .
 git commit -m 'Initial commit'
 
 echo ""
-echo "Yay! Your $project project '$project_name' is ready:"
+echo "Yay! Your $project project '$BEAMUP_PROJECT_NAME' is ready:"
 echo "  $project_dir"
 echo ""
 echo "  Run:"
-echo "  $  cd ./$project_name"
-
-fail () {
-  echo "Failed to create project: $1"
-  exit 1
-}
+echo "  $  cd ./$BEAMUP_PROJECT_NAME"
